[project]
name = "sports-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.121.0",
    "pydantic>=2.12.3",
    "pydantic-ai>=1.12.0",
    "pydantic-ai-litellm>=0.2.1",
    "uvicorn>=0.38.0",
]
